### ISSUE TITLE
感谢分享如此精妙的设计

### ISSUE THREAD

**Issue by lemyx** [Linusp/org-agenda-example#1]
新年好！

谢谢作者分享, 这一系统整合了柳比歇夫时间管理法和GTD的优点, Emacs 的 Org Mode 更是提供了一个绝佳的舞台

祝您龙年大吉, 心想事成 ❤️

**Comment by Linusp** [comment]
谢谢你的肯定和祝福，龙年快乐！

Issue 我就先关掉了，如果有具体问题可以再另外开 Issue 或者邮件联系我也可以哈。
